# Theme Settings
remote_theme: sevenzerothree/zero

# Site Settings
title: Zero by SevenZeroThree 
url                       : https://sevenzerothree.github.io
baseurl                   : /Zero/

# Github repositories
github_user: sevenzerothree
github_repo_url: https://github.com/sevenzerothree/zero/
