title                     : Zero
url                       : # https://sevenzerothree.github.io
baseurl                   : # /Zero

include: ["_pages"]

# Analytics
analytics:
  google_tracking_id      : # "UA-XXXXXXX-X"
  google_tag_manager_id   : # "GTM-XXXXX"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag